% Script: plot_path (Static Validation Version)

%% ===============================
%  LOAD DATA
% ================================

% Extract vehicle data
plot_path_vx = squeeze(out.pos_X.Data);
plot_path_vy = squeeze(out.pos_Y.Data);

% Waypoints
plot_path_wx = waypoints(:,1);
plot_path_wy = waypoints(:,2);

%% ===============================
%  MAIN TRAJECTORY PLOT
% ================================

figure('Color','w','Position',[100 100 900 650]);

hold on

% Reference path
plot(plot_path_wx,...
     plot_path_wy,...
     'k--',...
     'LineWidth',2.5);

% Vehicle path
plot(plot_path_vx,...
     plot_path_vy,...
     'b',...
     'LineWidth',2.8);

% Start/end markers
scatter(plot_path_wx(1),...
        plot_path_wy(1),...
        140,...
        'filled',...
        'MarkerFaceColor',[0 0.6 0]);

scatter(plot_path_wx(end),...
        plot_path_wy(end),...
        140,...
        'filled',...
        'MarkerFaceColor',[0.85 0 0]);

legend({'Reference Path',...
        'Tracked Path',...
        'Start',...
        'End'},...
        'Location','northoutside',...
        'Orientation','horizontal',...
        'Box','off');

xlabel('X Position (m)','FontSize',16,'FontWeight','bold');
ylabel('Y Position (m)','FontSize',16,'FontWeight','bold');

title('Vehicle Path Tracking Performance',...
      'FontSize',18,...
      'FontWeight','bold');

axis equal
grid on
box on

set(gca,...
    'FontSize',14,...
    'LineWidth',1.2,...
    'TickDir','out');

% Export high-res for poster
exportgraphics(gcf,...
'trajectory_tracking.png',...
'Resolution',600);

%% ===============================
% TRACKING ERROR
% ================================

figure('Color','w','Position',[100 100 900 500]);

plot(plot_path_error,...
    'LineWidth',2.5);

hold on

yline(mean(plot_path_error),...
      '--',...
      'Mean Error',...
      'LineWidth',1.8);

yline(max(plot_path_error),...
      ':',...
      'Max Error',...
      'LineWidth',1.8);

xlabel('Time Step',...
       'FontSize',16,...
       'FontWeight','bold');

ylabel('Cross-Track Error (m)',...
       'FontSize',16,...
       'FontWeight','bold');

title('Tracking Error Response',...
      'FontSize',18,...
      'FontWeight','bold');

grid on
box on

set(gca,...
    'FontSize',14,...
    'LineWidth',1.2,...
    'TickDir','out');

exportgraphics(gcf,...
'tracking_error.png',...
'Resolution',600);

%% ===============================
% PERFORMANCE METRICS
% ================================

fprintf('\n===== PERFORMANCE METRICS =====\n');
fprintf('Max Error : %.4f m\n',max(plot_path_error));
fprintf('Mean Error: %.4f m\n',mean(plot_path_error));
fprintf('RMS Error : %.4f m\n',sqrt(mean(plot_path_error.^2)));